#!/usr/bin/env python3
"""Derive the MediaPipe 478-index mirror table from a frontal symmetric face and
freeze it to vectra3d/_facemesh_mirror.py. Checks involution and known pairs."""
import json, sys, os
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from vectra3d.face_regions import mirror_map_from_landmarks, MIDLINE

KNOWN = {33: 263, 133: 362, 61: 291, 234: 454, 50: 280, 130: 359, 127: 356, 10: 10,
         152: 152, 468: 473, 70: 300, 21: 251, 54: 284, 58: 288, 172: 397, 136: 365}

L = np.asarray(json.load(open(sys.argv[1]))["landmarks"], float)
m = mirror_map_from_landmarks(L)
bad_inv = [i for i in range(478) if m[m[i]] != i]
bad_known = {k: (m[k], v) for k, v in KNOWN.items() if m[k] != v}
print("non-involutive:", len(bad_inv), bad_inv[:20])
print("known-pair mismatches:", bad_known)
mid_self = [i for i in MIDLINE if m[i] != i]
print("midline not self-mapped:", mid_self)
if bad_known or len(bad_inv) > 8:
    sys.exit("mirror table not trustworthy; fix before freezing")
pairs = sorted((i, m[i]) for i in range(478))
out = os.path.join(os.path.dirname(__file__), "..", "vectra3d", "_facemesh_mirror.py")
with open(out, "w") as f:
    f.write("# Generated by tools/build_mirror_map.py. MediaPipe 478-landmark mirror pairs.\n")
    f.write("PAIRS = " + repr(pairs) + "\n")
print("wrote", os.path.normpath(out))
